import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="font-sans">
      <body suppressHydrationWarning>
        <div className="min-w-full overflow-x-hidden">{children}</div>
      </body>
    </html>
  );
}
